backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'public/uploads' # Where media files will be stored
public_folder: '/uploads' # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: 'blogs'
    label: 'Blogs'
    description: 'Blog posts'
    folder: 'content/blogs'
    slug: '{{slug}}' # Filename template, e.g., title.md
    create: true
    fields:
      - { name: title, label: Title, widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD.MM.YYYY',
          time_format: 'HH:mm',
          format: 'LLL',
        }
      - {
          label: SEO Keywords,
          label_singular: Tag,
          name: pageKeywords,
          widget: list,
        }
      - { name: author, label: Author Name }
      - { name: profession, label: Author profession }
      - {
          name: authorAvatar,
          label: Author Avatar,
          widget: 'image',
          required: false,
        }
      - { name: category, label: Blog category, required: false }
      - {
          name: isFeatured,
          label: Is Featured,
          widget: 'boolean',
          required: false,
          default: false,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          name: contentDescription,
          label: Content Description mini,
          widget: markdown,
        }
      - { name: tags, label: Blog Tags, widget: list, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: 'product'
    label: 'Products'
    description: 'Ecommerce product'
    folder: 'content/products'
    slug: '{{slug}}' # Filename template, e.g., title.md
    create: true
    fields:
      - { name: productName, label: Product name, widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD.MM.YYYY',
          time_format: 'HH:mm',
          format: 'LLL',
        }
      - {
          label: SEO Keywords,
          label_singular: Tag,
          name: pageKeywords,
          widget: list,
        }
      - { name: category, label: Product category, required: false }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          name: contentDescription,
          label: Content Description,
          widget: 'string'
        }
      - { name: tags, label: Product Tags, widget: list, required: false }
      - { name: body, label: Product details, widget: markdown }
      - {
          name: isFeatured,
          label: Featured,
          widget: 'boolean',
          required: false,
          default: false,
        }
      - {
          name: isTopSeller,
          label: Top seller,
          widget: 'boolean',
          required: false,
          default: false,
        }
      - {
          name: isNewArrivals,
          label: New Arrival,
          widget: 'boolean',
          required: false,
          default: false,
        }
      - {
          name: price,
          label: Price,
          widget: 'number',
          required: true,
          value_type: 'float',
        }
      - {
          name: currency,
          label: Currency,
          widget: 'select',
          options: ['USD', 'EUR', 'GBP', 'NGN'],
          default: 'NGN',
          required: true,
        }
     