backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
<<<<<<< HEAD
media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
 - name: "blogs"
    label: "Blogs"
    description: "Blog posts"
    folder: "content/blogs"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true
    fields:
      - { name: title, label: Title, widget: "string" }
      - { name: pageDescription, label: Excerpt / Page Description }
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - { name: pageKeywords, label: SEO Keywords }
      - { name: author, label: Author Name }
      - { name: profession, label: Author profession }
      - { name: authorAvatar, label: Author Avatar }
      - { name: category, label: Blog category }
      - { name: contentDescription, label: Content Description mini }
      - { name: tags, label: Blog Tags, widget: list, required: false }
      - { name: cover, label: Blog Cover Link, required: false }
      - { name: body, label: Body, widget: markdown }
 - name: "trending"
    label: "Trending"
    description: "Blog posts"
    folder: "content/blogs"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true
    fields:
      - { name: title, label: Title, widget: "string" }
      - { name: pageDescription, label: Excerpt / Page Description }
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - { name: pageKeywords, label: SEO Keywords }
      - { name: author, label: Author Name }
      - { name: profession, label: Author profession }
      - { name: authorAvatar, label: Author Avatar }
      - { name: category, label: Blog category }
      - { name: contentDescription, label: Content Description mini }
      - { name: tags, label: Blog Tags, widget: list, required: false }
      - { name: cover, label: Blog Cover Link, required: false }
      - { name: body, label: Body, widget: markdown }
      
=======

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}
>>>>>>> 537839e4a13cad6434588ce97bb6c0355961a3a0
